/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Boxing Gym API
 * OpenAPI spec version: 0.1.0
 */
import { HttpClient, HttpParams } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';

// ─── Enums ────────────────────────────────────────────────────────────────────

export type PaymentType = typeof PaymentType[keyof typeof PaymentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentType = {
  monthly_fee: 'monthly_fee',
  material: 'material',
} as const;

export type PaymentMethod = typeof PaymentMethod[keyof typeof PaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethod = {
  cash: 'cash',
  transfer: 'transfer',
  bizum: 'bizum',
} as const;

// ─── Interfaces ───────────────────────────────────────────────────────────────

export interface PaymentCreate {
  student_id: string;
  type: PaymentType;
  /** Required when type is monthly_fee */
  period_year?: number;
  /** Required when type is monthly_fee */
  period_month?: number;
  amount: number;
  payment_method: PaymentMethod;
  /** Required when type is material */
  notes?: string | null;
}

export interface PaymentResponse {
  id: string;
  student_id: string;
  type: PaymentType;
  period_year?: number;
  period_month?: number;
  amount: number;
  payment_method: PaymentMethod;
  paid_at: string;
  created_by: string;
  notes?: string | null;
  created_at: string;
}

export interface PaginatedPaymentResponse {
  data: PaymentResponse[];
  total: number;
  limit: number;
  offset: number;
}

export interface PaymentSummaryStudent {
  student_id: string;
  student_name: string;
  paid_at?: string;
  amount?: number;
}

export interface AtRiskStudent {
  student_id: string;
  student_name: string;
  months_unpaid: number;
}

export interface PaymentSummary {
  period: string;
  paid: PaymentSummaryStudent[];
  pending: PaymentSummaryStudent[];
  overdue: PaymentSummaryStudent[];
  at_risk_of_inactivity: AtRiskStudent[];
}

export interface MethodBreakdown {
  count: number;
  amount: number;
}

export interface PaymentAnalytics {
  period: string;
  total_amount: number;
  total_payments: number;
  by_method: {
    cash?: MethodBreakdown;
    transfer?: MethodBreakdown;
    bizum?: MethodBreakdown;
  };
}

// ─── Query params ─────────────────────────────────────────────────────────────

export interface ListPaymentsParams {
  type?: PaymentType;
  period?: string;
  student_id?: string;
  payment_method?: PaymentMethod;
  limit?: number;
  offset?: number;
}

export interface GetPaymentSummaryParams {
  period?: string;
}

export interface GetPaymentAnalyticsParams {
  period?: string;
  type?: PaymentType;
}

export interface GetStudentPaymentsParams {
  limit?: number;
  offset?: number;
}

// ─── HTTP options ─────────────────────────────────────────────────────────────

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
    | HttpParams
    | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: { includeHeaders?: string[] } | boolean;
  timeout?: number;
}

// ─── Service ──────────────────────────────────────────────────────────────────

@Injectable({ providedIn: 'root' })
export class PaymentsAPIService {
  private readonly http = inject(HttpClient);

  /**
   * @summary Create Payment
   */
  createPaymentPaymentsPost<TData = PaymentResponse>(
    paymentCreate: PaymentCreate,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  createPaymentPaymentsPost<TData = PaymentResponse>(
    paymentCreate: PaymentCreate,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  createPaymentPaymentsPost<TData = PaymentResponse>(
    paymentCreate: PaymentCreate,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  createPaymentPaymentsPost<TData = PaymentResponse>(
    paymentCreate: PaymentCreate,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.post<TData>(`http://127.0.0.1:8000/payments`, paymentCreate, options as HttpClientOptions);
  }

  /**
   * @summary List Payments
   */
  listPaymentsPaymentsGet<TData = PaginatedPaymentResponse>(
    params?: ListPaymentsParams,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  listPaymentsPaymentsGet<TData = PaginatedPaymentResponse>(
    params?: ListPaymentsParams,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  listPaymentsPaymentsGet<TData = PaginatedPaymentResponse>(
    params?: ListPaymentsParams,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  listPaymentsPaymentsGet<TData = PaginatedPaymentResponse>(
    params?: ListPaymentsParams,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.get<TData>(`http://127.0.0.1:8000/payments`, {
      ...(options as HttpClientOptions),
      params: params as Record<string, string | number | boolean>,
    });
  }

  /**
   * @summary Get Payment Summary
   */
  getPaymentSummaryPaymentsSummaryGet<TData = PaymentSummary>(
    params?: GetPaymentSummaryParams,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getPaymentSummaryPaymentsSummaryGet<TData = PaymentSummary>(
    params?: GetPaymentSummaryParams,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getPaymentSummaryPaymentsSummaryGet<TData = PaymentSummary>(
    params?: GetPaymentSummaryParams,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getPaymentSummaryPaymentsSummaryGet<TData = PaymentSummary>(
    params?: GetPaymentSummaryParams,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.get<TData>(`http://127.0.0.1:8000/payments/summary`, {
      ...(options as HttpClientOptions),
      params: params as Record<string, string | number | boolean>,
    });
  }

  /**
   * @summary Get Payment Analytics
   */
  getPaymentAnalyticsPaymentsAnalyticsGet<TData = PaymentAnalytics>(
    params?: GetPaymentAnalyticsParams,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getPaymentAnalyticsPaymentsAnalyticsGet<TData = PaymentAnalytics>(
    params?: GetPaymentAnalyticsParams,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getPaymentAnalyticsPaymentsAnalyticsGet<TData = PaymentAnalytics>(
    params?: GetPaymentAnalyticsParams,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getPaymentAnalyticsPaymentsAnalyticsGet<TData = PaymentAnalytics>(
    params?: GetPaymentAnalyticsParams,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.get<TData>(`http://127.0.0.1:8000/payments/analytics`, {
      ...(options as HttpClientOptions),
      params: params as Record<string, string | number | boolean>,
    });
  }

  /**
   * @summary Get Payment
   */
  getPaymentPaymentsPaymentIdGet<TData = PaymentResponse>(
    paymentId: string,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getPaymentPaymentsPaymentIdGet<TData = PaymentResponse>(
    paymentId: string,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getPaymentPaymentsPaymentIdGet<TData = PaymentResponse>(
    paymentId: string,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getPaymentPaymentsPaymentIdGet<TData = PaymentResponse>(
    paymentId: string,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.get<TData>(`http://127.0.0.1:8000/payments/${paymentId}`, options as HttpClientOptions);
  }

  /**
   * @summary Delete Payment
   */
  deletePaymentPaymentsPaymentIdDelete<TData = void>(
    paymentId: string,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  deletePaymentPaymentsPaymentIdDelete<TData = void>(
    paymentId: string,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  deletePaymentPaymentsPaymentIdDelete<TData = void>(
    paymentId: string,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  deletePaymentPaymentsPaymentIdDelete<TData = void>(
    paymentId: string,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.delete<TData>(`http://127.0.0.1:8000/payments/${paymentId}`, options as HttpClientOptions);
  }

  /**
   * @summary Get Student Payments
   */
  getStudentPaymentsStudentsStudentIdPaymentsGet<TData = PaginatedPaymentResponse>(
    studentId: string,
    params?: GetStudentPaymentsParams,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  getStudentPaymentsStudentsStudentIdPaymentsGet<TData = PaginatedPaymentResponse>(
    studentId: string,
    params?: GetStudentPaymentsParams,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  getStudentPaymentsStudentsStudentIdPaymentsGet<TData = PaginatedPaymentResponse>(
    studentId: string,
    params?: GetStudentPaymentsParams,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  getStudentPaymentsStudentsStudentIdPaymentsGet<TData = PaginatedPaymentResponse>(
    studentId: string,
    params?: GetStudentPaymentsParams,
    options?: HttpClientOptions & { observe?: unknown },
  ): Observable<unknown> {
    return this.http.get<TData>(`http://127.0.0.1:8000/students/${studentId}/payments`, {
      ...(options as HttpClientOptions),
      params: params as Record<string, string | number | boolean>,
    });
  }
}

export type CreatePaymentPaymentsPostClientResult = NonNullable<PaymentResponse>;
export type ListPaymentsPaymentsGetClientResult = NonNullable<PaginatedPaymentResponse>;
export type GetPaymentSummaryPaymentsSummaryGetClientResult = NonNullable<PaymentSummary>;
export type GetPaymentAnalyticsPaymentsAnalyticsGetClientResult = NonNullable<PaymentAnalytics>;
export type GetPaymentPaymentsPaymentIdGetClientResult = NonNullable<PaymentResponse>;
export type DeletePaymentPaymentsPaymentIdDeleteClientResult = NonNullable<void>;
export type GetStudentPaymentsStudentsStudentIdPaymentsGetClientResult =
  NonNullable<PaginatedPaymentResponse>;
