/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Boxing Gym API
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type StudentCreatePhone = string | null;

export type StudentCreateWeight = number | null;

export interface StudentCreate {
  /**
   * @minLength 2
   * @maxLength 100
   */
  full_name: string;
  email: string;
  phone?: StudentCreatePhone;
  birth_date: string;
  enrollment_date: string;
  level: StudentLevel;
  is_active?: boolean;
  weight?: StudentCreateWeight;
}

export type StudentLevel = typeof StudentLevel[keyof typeof StudentLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentLevel = {
  beginner: 'beginner',
  intermediate: 'intermediate',
  advanced: 'advanced',
} as const;

export type StudentResponsePhone = string | null;

export type StudentResponseWeight = number | null;

export interface StudentResponse {
  /**
   * @minLength 2
   * @maxLength 100
   */
  full_name: string;
  email: string;
  phone?: StudentResponsePhone;
  birth_date: string;
  enrollment_date: string;
  level: StudentLevel;
  is_active?: boolean;
  weight?: StudentResponseWeight;
  id: string;
  created_at: string;
  updated_at: string;
}

export type StudentUpdateFullName = string | null;

export type StudentUpdateEmail = string | null;

export type StudentUpdatePhone = string | null;

export type StudentUpdateBirthDate = string | null;

export type StudentUpdateLevel = StudentLevel | null;

export type StudentUpdateIsActive = boolean | null;

export type StudentUpdateWeight = number | null;

export interface StudentUpdate {
  full_name?: StudentUpdateFullName;
  email?: StudentUpdateEmail;
  phone?: StudentUpdatePhone;
  birth_date?: StudentUpdateBirthDate;
  level?: StudentUpdateLevel;
  is_active?: StudentUpdateIsActive;
  weight?: StudentUpdateWeight;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class BoxingGymAPIService {
  private readonly http = inject(HttpClient);
/**
 * @summary List Students
 */
 listStudentsStudentsGet<TData = StudentResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 listStudentsStudentsGet<TData = StudentResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 listStudentsStudentsGet<TData = StudentResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  listStudentsStudentsGet<TData = StudentResponse[]>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://127.0.0.1:8000/students/`,options
    );
  }

/**
 * @summary Create Student
 */
 createStudentStudentsPost<TData = StudentResponse>(studentCreate: StudentCreate, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 createStudentStudentsPost<TData = StudentResponse>(studentCreate: StudentCreate, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 createStudentStudentsPost<TData = StudentResponse>(studentCreate: StudentCreate, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  createStudentStudentsPost<TData = StudentResponse>(
    studentCreate: StudentCreate, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `http://127.0.0.1:8000/students/`,
      studentCreate,options
    );
  }

/**
 * @summary Get Student
 */
 getStudentStudentsStudentIdGet<TData = StudentResponse>(studentId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getStudentStudentsStudentIdGet<TData = StudentResponse>(studentId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getStudentStudentsStudentIdGet<TData = StudentResponse>(studentId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getStudentStudentsStudentIdGet<TData = StudentResponse>(
    studentId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://127.0.0.1:8000/students/${studentId}`,options
    );
  }

/**
 * @summary Update Student
 */
 updateStudentStudentsStudentIdPatch<TData = StudentResponse>(studentId: string,
    studentUpdate: StudentUpdate, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 updateStudentStudentsStudentIdPatch<TData = StudentResponse>(studentId: string,
    studentUpdate: StudentUpdate, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 updateStudentStudentsStudentIdPatch<TData = StudentResponse>(studentId: string,
    studentUpdate: StudentUpdate, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  updateStudentStudentsStudentIdPatch<TData = StudentResponse>(
    studentId: string,
    studentUpdate: StudentUpdate, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.patch<TData>(
      `http://127.0.0.1:8000/students/${studentId}`,
      studentUpdate,options
    );
  }

/**
 * @summary Delete Student
 */
 deleteStudentStudentsStudentIdDelete<TData = void>(studentId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteStudentStudentsStudentIdDelete<TData = void>(studentId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteStudentStudentsStudentIdDelete<TData = void>(studentId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteStudentStudentsStudentIdDelete<TData = void>(
    studentId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(
      `http://127.0.0.1:8000/students/${studentId}`,options
    );
  }

/**
 * @summary Health Check
 */
 healthCheckHealthGet<TData = unknown>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 healthCheckHealthGet<TData = unknown>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 healthCheckHealthGet<TData = unknown>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  healthCheckHealthGet<TData = unknown>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `http://127.0.0.1:8000/health`,options
    );
  }

};

export type ListStudentsStudentsGetClientResult = NonNullable<StudentResponse[]>
export type CreateStudentStudentsPostClientResult = NonNullable<StudentResponse>
export type GetStudentStudentsStudentIdGetClientResult = NonNullable<StudentResponse>
export type UpdateStudentStudentsStudentIdPatchClientResult = NonNullable<StudentResponse>
export type DeleteStudentStudentsStudentIdDeleteClientResult = NonNullable<void>
export type HealthCheckHealthGetClientResult = NonNullable<unknown>
