import 'reflect-metadata';
import 'dotenv/config';
import mongoose from 'mongoose';
import { MessageType } from '../src/messages/schemas/message.schema';

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error('Missing MONGODB_URI in .env');
  process.exit(1);
}

const MessageSchema = new mongoose.Schema(
  {
    code: { type: String, required: true, unique: true, uppercase: true },
    audienceType: { type: String, required: true },
    recipientName: { type: String, default: null },
    isActive: { type: Boolean, default: true },
    slides: { type: [Object], required: true },
  },
  { timestamps: true },
);

const MessageModel = mongoose.model('Message', MessageSchema, 'messages');

const messages = [
  {
    code: 'REI',
    audienceType: 'friends',
    recipientName: 'Reinaldo Perez',
    isActive: true,
    slides: [
      {
        title: 'Buenas mi rei!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres mi mejor amigo, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Como pasan los años.',
        body: 'Esta foto es de antes de migrar a Madrid',
        image: '/assets/stories/rei_bef_migra.jpg',
        altText: 'Reinaldo y yo en un cumpleaños',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Eres una persona muy especial para mi.',
      },
      {
        title: 'Gracias por cuidar de mi en mis momentos mas dificiles',
        body: 'Has cuidado de mi familia',
        messageType: MessageType.TEXT,
        footer: 'No sabes lo mucho que estoy agradecido por todo lo que haces por mi.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Años despues',
        body: 'Recreamos la mitica foto',
        image: '/assets/stories/rei_aft_migra.jpg',
        altText: 'Luis y yo en la playa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Pasan los años y seguimos compartiendo buenos momentos',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Has sido ese amigo especial que siempre estuvo para mi',
        body: 'Pero no te descuides',
        image: '/assets/stories/rei_y_yo.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Igual te puedo reventar a cahcetadas mmg.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'TORRES',
    audienceType: 'friends',
    recipientName: 'Luis Torres',
    isActive: true,
    slides: [
      {
        title: 'Buenas Manitoooo!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres mi mejor amigo, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Como pasan los años.',
        body: 'Has estado en momentos muy importantes en mi vida.',
        image: '/assets/stories/luis_y_yo_graduacion.jpg',
        altText: 'Luis y yo en despues de mi graduacion',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Es algo que me encantaria agradecer, en las buenas y en las malas.',
      },
      {
        title: 'Fuiste ese primer amigo que tuve de verdad.',
        body: 'Me abriste las puertas de tu grupo y de tu casa.',
        messageType: MessageType.TEXT,
        footer: 'Aunque te parezca raro, recibirme fue una de las mejores cosas que me ha pasado.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Momentos...',
        body: 'Este día casi nos desviven a ambos.',
        image: '/assets/stories/luis_playa.jpg',
        altText: 'Luis y yo en la playa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Sin embargo, seguimos vivos y super unidos a pesar de la distancia.',
      },
      {
        title: 'Borracheras...',
        body: 'No tenemos fotos de la mayoria de ellas',
        image: '/assets/stories/luis_borrachera.jpg',
        altText: 'Luis y yo en la playa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Pero que buenos momentos nos pegamos',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Gracias por existir.',
        body: 'No imagino mi vida sin todo lo que hemos vivido.',
        messageType: MessageType.TEXT,
        footer: 'Agradezco todo lo que has hecho por mi y por nuestra amistad.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'JONY',
    audienceType: 'friends',
    recipientName: 'Jonathan Gomez',
    isActive: true,
    slides: [
      {
        title: 'Manitoooo!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres de los mios.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Tengo la suerte de tener a gente como tú en mi vida',
        body: 'Contigo comenzó todo este camino.',
        messageType: MessageType.TEXT,
        footer: 'Que me ofrecieras la oportunidad de cambiar de empresa valió mucho para mi.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Has sido un gran apoyo en este tiempo',
        body: 'Siempre me has llenado de muy buena energia.',
        messageType: MessageType.TEXT,
        footer: 'Me has servido de desahogo en esos momentos difíciles.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre has estado al tanto de todo y me has podido apoyar cuando lo he necesitado.',
      },
      {
        title: 'Gracias por tanto.',
        body: 'Siempre estas al pie de cañon cuando lo necesito.',
        messageType: MessageType.TEXT,
        footer: 'Gracias por tanto y disculpa lo poco.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'MIGUEL',
    audienceType: 'family',
    recipientName: 'Miguel Adames',
    isActive: true,
    slides: [
      {
        title: 'Bendición tío favorito! 🥰',
        messageType: MessageType.INTRO,
        body: 'Gracias por ser esa persona que siempre estuvo para mí.',
        footer: 'Siempre me ha consentido y me ha cuidado en cada momento, gracias!',
      },
      {
        title: 'Siempre apoyándome en todo',
        body: 'Sin importar la locura o lo que fuera',
        image: '/assets/stories/miguel_y_yo.jpg',
        altText: 'Miguel y yo',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre era un si a todo, un apoyo incondicional.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Gracias por tanto.',
        body: 'Siempre fue mi tío favorito.',
        messageType: MessageType.TEXT,
        footer: 'Le debo mucho por las enseñanzas que me ha dado.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'SONIA',
    audienceType: 'family',
    recipientName: 'Sonia Adames',
    isActive: true,
    slides: [
      {
        title: 'Bendición tía! 🥰',
        messageType: MessageType.INTRO,
        body: 'Gracias por ser mi tía, mi madrina y esa persona que siempre estuvo para mí.',
        footer: 'Desde pequeño tengo recuerdos de usted, cuidándome y consintiéndome en cada momento.',
      },
      {
        title: 'Siempre divertida',
        body: 'Nunca faltaba un momento donde pudieramos reirnos y pasarlo bien.',
        image: '/assets/stories/sonia_divertida.jpg',
        altText: 'sonia y yo',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias por sacarme una sonrisa cada vez que lo necesitaba.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'Una fuente de inspiración',
        body: 'Siempre la he tenido como un pilar de lo que esta bien.',
        image: '/assets/stories/pilares.jpg',
        altText: 'Mis pilares',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias por cuidar de mi en mis momentos mas dificiles.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'VERU',
    audienceType: 'family',
    recipientName: 'Veruska Indriago',
    isActive: true,
    slides: [
      {
        title: 'Buenas marica!',
        messageType: MessageType.INTRO,
        body: 'Gracias por cubrirme la espalda desde que eramos niños',
        footer: 'A pesar de la distancia, siempre hemos intentado estar conectados.',
      },
      {
        title: 'Desde pequeños',
        body: 'Toda la vida hemos estado jodiendo juntos',
        image: '/assets/stories/veru.jpg',
        altText: 'veru y yo',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'En cualquier aventura o pelea, siempre estabas a mi lado.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'Aunque no estemos juntos',
        body: 'Se que siempre voy a contar con ustedes.',
        image: '/assets/stories/3_mosqueteros.jpg',
        altText: 'Los 3 mosqueteros',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre me han cuidado la espalda.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'SHOMA',
    audienceType: 'family',
    recipientName: 'Shomaly Indriago',
    isActive: true,
    slides: [
      {
        title: 'Buenas mi niña!',
        messageType: MessageType.INTRO,
        body: 'Siempre te he considerado mi hermanita pequeña',
        footer: 'A pesar de la distancia, siempre he intentado estar cerca de ti.',
      },
      {
        title: 'Desde pequeños en la aventura',
        body: 'Creo que siempre has estado detrás de mi inventando',
        image: '/assets/stories/shoma_y_yo_moto.jpg',
        altText: 'Shoma y yo en la moto',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'En cualquier aventura que nos proponiamos, siempre hemos estado juntos.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'En mi gran aventura',
        body: 'Mi foto favorita es la que tengo contigo',
        image: '/assets/stories/shoma_feliz.jpg',
        altText: 'Shoma y yo en NY',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'La imagen transmite mucha felicidad.',
      },
      {
        title: 'Aunque no estemos juntos',
        body: 'Se que siempre voy a contar con ustedes.',
        image: '/assets/stories/3_mosqueteros.jpg',
        altText: 'Los 3 mosqueteros',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre me han cuidado la espalda.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'ALE',
    audienceType: 'friends',
    recipientName: 'Alejandro Gonzalez Santiago',
    isActive: true,
    slides: [
      {
        title: 'Mi Aleeeeeee!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres mi mejor amigo, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Tengo la suerte de tener a gente como tú en mi vida',
        body: 'Siempre has estado para mi, en las buenas y en las malas.',
        messageType: MessageType.TEXT,
        footer: 'No tengo palabras para agradecerte.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Has sido un gran apoyo en este tiempo',
        body: 'Siempre me has llenado de muy buena energia.',
        messageType: MessageType.TEXT,
        footer: 'Aunque no estuvieras en tu mejor momento, lo has dado todo para ayudarme.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre has estado al tanto de todo y me has podido apoyar cuando lo he necesitado.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'IRE',
    audienceType: 'friends',
    recipientName: 'Ireiba Villalobos',
    isActive: true,
    slides: [
      {
        title: 'Negraaaaaa!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres de los mias, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Siempre has buscado cuidarme y ayudarme',
        body: 'Te agradezco por ser buena conmigo en todo momento.',
        messageType: MessageType.TEXT,
        footer: 'Por soportarme en los momentos más difíciles.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre has estado al tanto de todo y me has podido apoyar cuando lo he necesitado.',
      },
      {
        title: 'Eckson y tu son parte de mi familia',
        body: 'Con lo bueno, lo malo y lo que sea, siempre serán uno de los mios.',
        image: '/assets/stories/ireckson.jpg',
        altText: 'Ire y eso con nosotros',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Nos quedan muchas parrillas y bebederas por hacer juntos.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'ECK',
    audienceType: 'friends',
    recipientName: 'Eckson Romero',
    isActive: true,
    slides: [
      {
        title: 'Negrooooooo!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres de los mios, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Tengo la suerte de tener a gente como tú en mi vida',
        body: 'Me has apoyado en todo momento, me ayudaste en momentos muy difíciles.',
        messageType: MessageType.TEXT,
        footer: 'Te debo mucho.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Siempre has estado para mi.',
        body: 'Te agradezco por estar disponible siempre y ser un gran amigo.',
        messageType: MessageType.TEXT,
        footer: 'Y por las parrillas, las bebederas y los buenos momentos que hemos pasado juntos.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre has estado al tanto de todo y me has podido apoyar cuando lo he necesitado.',
      },
      {
        title: 'Ire y tu son parte de mi familia',
        body: 'Con lo bueno, lo malo y lo que sea, siempre serán uno de los mios.',
        image: '/assets/stories/ireckson.jpg',
        altText: 'Ire y eso con nosotros',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Que lo bueno siempre prime sobre lo malo.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'CAMPOS',
    audienceType: 'friends',
    recipientName: 'Gabriel Campos',
    isActive: true,
    slides: [
      {
        title: 'Buenas Campitos!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres mi mejor amigo, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Como pasan los años.',
        body: 'Jóvenes y sin saber que nos esperaba.',
        image: '/assets/stories/campos_y_yo_playa.jpg',
        altText: 'Campos y yo en la playa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'La pasabamos bien, cuantas cosas hemos hecho juntos.',
      },
      {
        title: 'Nos encontramos de nuevo en Madrid',
        body: 'Las vueltas de la vida y sus cosas que nos han llevado a estar juntos de nuevo.',
        image: '/assets/stories/campos_y_yo_soporte.jpg',
        altText: 'Campos y yo haciendo de soporte el uno al otro',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Para poder ser el soporte del otro en los momentos más difíciles.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Tengo la suerte de tener a gente como tú en mi vida',
        body: 'Me has apoyado en muchos momentos, me has ayudado a ser mejor y me has hecho reir.',
        image: '/assets/stories/campitos_cool.jpg',
        altText: 'Campos en modo cool',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Eres uno de mis mejores amigos, uno de los más importantes en mi vida.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Aventuras que vivimos juntos',
        body: 'Nunca me olvidaré de tu despedida, creo que la pasaste muy bien.',
        image: '/assets/stories/campitos_aleman.jpg',
        altText: 'Campitos aleman',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'El alemán de nuestro corazones.',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Te he intentado mantener un poco al tanto, pero se que igual me has estado apoyando.',
      },
      {
        title: 'Me alegra mucho seguir compartiendo logros contigo',
        body: 'Creo que tu graduación ha sido uno de los que mas me ha llenado de orgullo.',
        image: '/assets/stories/campos_graduacion.jpg',
        altText: 'Campos graduandose',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Que grande eres, puedes lograr todo lo que te propongas.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'FRAN',
    audienceType: 'friends',
    recipientName: 'Francisco Chakian',
    isActive: true,
    slides: [
      {
        title: 'Mi Fraaaaaaan!',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres mi mejor amigo, una de las personas más importantes en mi vida.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Tengo la suerte de tener a gente como tú en mi vida',
        body: 'Me has apoyado en muchos momentos, me has ayudado a ser mejor y me has hecho reir.',
        image: '/assets/stories/frank.jpg',
        altText: 'Fran y yo en el madrid',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Has sido como un hermano mayor para mi. ',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Siempre has estado al tanto de todo y me has podido apoyar cuando lo he necesitado.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'CHAMBAFORCE',
    audienceType: 'friends',
    recipientName: null,
    isActive: true,
    slides: [
      {
        title: 'Buenas mi gente',
        messageType: MessageType.INTRO,
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres de los mios.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Cuantas cosas hemos logrado en este tiempo',
        body: 'Hemos logrado la promoción, hemos viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Has sido un gran apoyo en este tiempo.',
      },
      {
        title: 'De tantas cosas',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'FRIENDSE',
    audienceType: 'friends',
    recipientName: null,
    isActive: true,
    slides: [
      {
        title: 'Buenas mis reyes',
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        footer: 'Pero debes saber que eres de los mios.',
        messageType: MessageType.INTRO,
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'Tuve la suerte de encontrarme con Alba, es una persona muy especial para mi.',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Capaz no les he mantenido al tanto de todo esto',
      },
      {
        title: 'De tantas cosas que han pasado',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'FRIENDSOE',
    audienceType: 'friends',
    recipientName: null,
    isActive: true,
    slides: [
      {
        title: 'Buenas mis reyes',
        body: 'Ha pasado mucho tiempo desde que nos conocimos',
        messageType: MessageType.INTRO,
        footer: 'Pero debes saber que eres de los mios.',
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'He conocido a alguien muy especial, ella es Alba (por si aún no la conoces)',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Capaz no te he mantenido al tanto de todo esto.',
      },
      {
        title: 'De tantas cosas que han pasado',
        body: 'Quería compartir una noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque eres muy importante para mi.',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Te quiero y quería que lo supieras de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
  {
    code: 'FAMILY',
    audienceType: 'family',
    recipientName: 'Familia',
    isActive: true,
    slides: [
      {
        title: 'Hola familia',
        body: 'A pesar de que estamos muy lejos, siempre he intentado estar cerca de ustedes.',
        footer: 'Porque son todo para mi',
        messageType: MessageType.INTRO,
      },
      {
        title: 'Este último año ha sido difícil',
        body: 'Fue un tiempo de cambios, decisiones y una búsqueda de mi verdadero yo.',
        image: '/assets/stories/feliz.jpg',
        altText: 'Yo siendo Feliz despues de la anestesia',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Gracias a eso estoy pudiendo disfrutar de la vida y ser muy feliz.',
      },
      {
        title: 'Entre toda esta aventura',
        body: 'He conocido a alguien muy especial, ella es Alba (por si aún no la conoces)',
        image: '/assets/stories/alba.jpg',
        altText: 'El amor de mi vida',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Me está haciendo muy feliz',
      },
      {
        title: 'Han pasado tantas cosas en este tiempo',
        body: 'Me han ascendido en el trabajo, he viajado a trabajar a diferentes paises y he podido disfrutar de la vida.',
        image: '/assets/stories/ascenso.jpg',
        altText: 'Yo en la empresa',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Capaz no te he mantenido al tanto de todo esto.',
      },
      {
        title: 'De tantas cosas que han pasado',
        body: 'Quería compartir esta noticia de una forma especial.',
        messageType: MessageType.TEXT,
        footer: 'Porque ustedes lo son todo',
      },
      {
        title: '',
        body: '',
        messageType: MessageType.COUNTDOWN,
        footer: '',
      },
      {
        title: '¡Seremos papás!',
        body: 'Los quiero mucho y quería que lo supieran de una forma especial.',
        image: '/assets/stories/ultrasound.jpg',
        altText: 'Foto del segundo eco, ya le latia el corazón',
        messageType: MessageType.ULTRASOUND_REVEAL,
        footer: 'La familia seguirá creciendo',
      },
      {
        title: 'Estamos en el primer trimestre',
        body: 'Como puedes ver, ya tiene formita.',
        image: '/assets/stories/semana12.jpg',
        altText: 'Eco de los 3 meses de embarazo',
        messageType: MessageType.FINAL_REVEAL,
        footer: 'Este es el eco de la semana 12.',
      },
      {
        title: 'Todo va bien y estamos tranquilos.',
        body: 'La madre no ha tenido ningún mal síntoma y el bichito va creciendo bien.',
        image: '/assets/stories/pareja.jpg',
        altText: 'Felices y contentos',
        messageType: MessageType.TEXT_IMAGE,
        footer: 'Queremos compartir contigo este momento tan especial y feliz.',
      },
    ],
  },
];

async function seed() {
  await mongoose.connect(MONGODB_URI!, { dbName: 'announcement' });
  console.log('Connected to MongoDB');

  const codes = messages.map((m) => m.code);
  await MessageModel.deleteMany({ code: { $in: codes } });
  console.log('Cleared existing demo messages');

  await MessageModel.insertMany(messages);
  console.log(`Seeded ${messages.length} messages: ${codes.join(', ')}`);

  await mongoose.disconnect();
  console.log('Done.');
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
