name: Chromatic

on:
  push:
    branches:
      - main
    paths:
      - 'projects/design-system/**'
      - '.storybook/**'
      - 'package.json'
  pull_request:
    branches:
      - main
    paths:
      - 'projects/design-system/**'
      - '.storybook/**'
      - 'package.json'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
